export const genomes = [
    {
        "id": "hg38",
        "name": "Human (GRCh38/hg38)",
        "fastaURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg38/hg38.fa",
        "indexURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg38/hg38.fa.fai",
        "cytobandURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/hg38/cytoBandIdeo.txt.gz",
        "aliasURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/hg38/hg38_alias.tab",
        "chromSizesURL": "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.chrom.sizes",
        "twoBitURL": "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/hg38.2bit",
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/ncbiRefSeq.txt.gz",
                "indexed": false,
                "order": 1000001,
                "infoURL": "https://www.ncbi.nlm.nih.gov/gene/?term=$$"
            }
        ],
        "chromosomeOrder": "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY",
        "description": "Dec. 2013 (GRCh38/hg38)",
        "nibPath": "/gbdb/hg38",
        "organism": "Human",
        "defaultPos": "chr7:155799529-155812871",
        "active": 1,
        "orderKey": 50,
        "genome": "Human",
        "scientificName": "Homo sapiens",
        "htmlPath": "/gbdb/hg38/html/description.html",
        "hgNearOk": 1,
        "hgPbOk": 0,
        "sourceName": "GRCh38 Genome Reference Consortium Human Reference 38 (GCA_000001405.15)",
        "taxId": 9606,
        "evaSpecies": "hsapiens_grch38",
        "trackHubId": "GCA_000001405.15"
    },
    {
        "id": "hg19",
        "name": "Human (GRCh37/hg19)",
        "fastaURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg19/hg19.fasta",
        "indexURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg19/hg19.fasta.fai",
        "cytobandURL": "https://igv-genepattern-org.s3.amazonaws.com/genomes/seq/hg19/cytoBand.txt",
        "aliasURL": "https://s3.amazonaws.com/igv.org.genomes/hg19/hg19_alias.tab",
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "id": "hg19_genes",
                "url": "https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ncbiRefSeq.txt.gz",
                "indexed": false,
                "order": 1000000,
                "infoURL": "https://www.ncbi.nlm.nih.gov/gene/?term=$$"
            }
        ],
        "chromosomeOrder": "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY",
        "description": "Feb. 2009 (GRCh37/hg19)",
        "nibPath": "/gbdb/hg19",
        "organism": "Human",
        "defaultPos": "chr7:155592223-155605565",
        "active": 1,
        "orderKey": 60,
        "genome": "Human",
        "scientificName": "Homo sapiens",
        "htmlPath": "/gbdb/hg19/html/description.html",
        "hgNearOk": 1,
        "hgPbOk": 0,
        "sourceName": "GRCh37 Genome Reference Consortium Human Reference 37 (GCA_000001405.1)",
        "taxId": 9606,
        "evaSpecies": "hsapiens_grch37",
        "trackHubId": "GCA_000001405.1"
    },
    {
        "id": "mm39",
        "name": "Mouse (GRCm39/mm39)",
        "fastaURL": "https://s3.amazonaws.com/igv.org.genomes/mm39/mm39.fa",
        "indexURL": "https://s3.amazonaws.com/igv.org.genomes/mm39/mm39.fa.fai",
        "cytobandURL": "https://hgdownload.soe.ucsc.edu/goldenPath/mm39/database/cytoBandIdeo.txt.gz",
        "aliasURL": "https://s3.amazonaws.com/igv.org.genomes/mm39/mm39_alias.tab",
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://hgdownload.soe.ucsc.edu/goldenPath/mm39/database/ncbiRefSeq.txt.gz",
                "indexed": false,
                "order": 1000000
            }
        ],
        "chromosomeOrder": "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chrX,chrY",
        "description": "Jun. 2020 (GRCm39/mm39)",
        "nibPath": "/gbdb/mm39",
        "organism": "Mouse",
        "defaultPos": "chr12:56741761-56761390",
        "active": 1,
        "orderKey": 269,
        "genome": "Mouse",
        "scientificName": "Mus musculus",
        "htmlPath": "/gbdb/mm39/html/description.html",
        "hgNearOk": 1,
        "hgPbOk": 0,
        "sourceName": "Genome Reference Consortium Mouse Build 39 (GCA_000001635.9)",
        "taxId": 10090,
        "evaSpecies": "mmusculus_grcm39",
        "trackHubId": "GCA_000001635.9"
    },
    {
        "id": "mm10",
        "name": "Mouse (GRCm38/mm10)",
        "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/mm10/mm10.fa",
        "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/mm10/mm10.fa.fai",
        "cytobandURL": "https://s3.amazonaws.com/igv.broadinstitute.org/annotations/mm10/cytoBandIdeo.txt.gz",
        "order": 1000000,
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://hgdownload.soe.ucsc.edu/goldenPath/mm10/database/ncbiRefSeq.txt.gz",
                "indexed": false,
                "order": 1000000
            }
        ],
        "chromosomeOrder": "chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chrX,chrY",
        "description": "Dec. 2011 (GRCm38/mm10)",
        "nibPath": "/gbdb/mm10",
        "organism": "Mouse",
        "defaultPos": "chr12:56694976-56714605",
        "active": 1,
        "orderKey": 270,
        "genome": "Mouse",
        "scientificName": "Mus musculus",
        "htmlPath": "/gbdb/mm10/html/description.html",
        "hgNearOk": 1,
        "hgPbOk": 0,
        "sourceName": "Genome Reference Consortium Mouse Build 38 (GCA_000001635.2)",
        "taxId": 10090,
        "evaSpecies": "mmusculus_grcm38",
        "trackHubId": "GCA_000001635.2"
    },
    {
        "id": "rn6",
        "name": "Rat (RGCS 6.0/rn6)",
        "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/rn6/rn6.fa",
        "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/rn6/rn6.fa.fai",
        "cytobandURL": "https://s3.amazonaws.com/igv.org.genomes/rn6/cytoBand.txt.gz",
        "order": 1000000,
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://s3.amazonaws.com/igv.org.genomes/rn6/ncbiRefSeq.sorted.txt.gz",
                "indexURL": "https://s3.amazonaws.com/igv.org.genomes/rn6/ncbiRefSeq.sorted.txt.gz.tbi",
                "order": 1000000,
                "supportsWholeGenome": false,
                "visibilityWindow": -1
            },
            {
                "name": "Genes",
                "format": "bed",
                "url": "https://s3.amazonaws.com/igv.org.genomes/locations/geneLocations_rn6.bed.gz",
                "hidden": true,
                "searchable": true
            }
        ],
        "description": "Jul. 2014 (RGSC 6.0/rn6)",
        "nibPath": "/gbdb/rn6",
        "organism": "Rat",
        "defaultPos": "chr1:80608553-80639261",
        "active": 1,
        "orderKey": 18031,
        "genome": "Rat",
        "scientificName": "Rattus norvegicus",
        "htmlPath": "/gbdb/rn6/html/description.html",
        "hgNearOk": 0,
        "hgPbOk": 0,
        "sourceName": "RGSC Rnor_6.0 (GCA_000001895.4)",
        "taxId": 10116,
        "evaSpecies": "rnorvegicus_60",
        "trackHubId": "GCA_000001895.4"
    },
    {
        "id": "danRer10",
        "name": "Zebrafish (GRCZ10/danRer10)",
        "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/danRer10/danRer10.fa",
        "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/danRer10/danRer10.fa.fai",
        "cytobandURL": "https://s3.amazonaws.com/igv.org.genomes/danRer10/cytoBandIdeo.txt.gz",
        "order": 1000000,
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://s3.amazonaws.com/igv.org.genomes/danRer10/ncbiRefSeq.sorted.txt.gz",
                "indexURL": "https://s3.amazonaws.com/igv.org.genomes/danRer10/ncbiRefSeq.sorted.txt.gz.tbi",
                "order": 1000000,
                "visibilityWindow": -1,
                "supportsWholeGenome": false
            },
            {
                "name": "Genes",
                "format": "bed",
                "url": "https://s3.amazonaws.com/igv.org.genomes/locations/geneLocations_danRer10.bed.gz",
                "hidden": true,
                "searchable": true
            }
        ],
        "description": "Sep. 2014 (GRCz10/danRer10)",
        "nibPath": "/gbdb/danRer10",
        "organism": "Zebrafish",
        "defaultPos": "chr10:33840892-34129251",
        "active": 1,
        "orderKey": 26173,
        "genome": "Zebrafish",
        "scientificName": "Danio rerio",
        "htmlPath": "/gbdb/danRer10/html/description.html",
        "hgNearOk": 0,
        "hgPbOk": 0,
        "sourceName": "Genome Reference Consortium Zebrafish Build 10 (GCA_000002035.3)",
        "taxId": 7955,
        "evaSpecies": "drerio_grcz10",
        "trackHubId": "GCA_000002035.3"
    },
    {
        "id": "ce11",
        "name": "C. elegans (ce11)",
        "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/ce11/ce11.fa",
        "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/ce11/ce11.fa.fai",
        "cytobandURL": "https://s3.amazonaws.com/igv.org.genomes/ce11/cytoBandIdeo.txt.gz",
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://s3.amazonaws.com/igv.org.genomes/ce11/refGene.sorted.txt.gz",
                "indexed": false,
                "order": 1000000,
                "searchable": true
            }
        ],
        "description": "Feb. 2013 (WBcel235/ce11)",
        "nibPath": "/gbdb/ce11",
        "organism": "C. elegans",
        "defaultPos": "chrII:14646376-14667875",
        "active": 1,
        "orderKey": 3024,
        "genome": "C. elegans",
        "scientificName": "Caenorhabditis elegans",
        "htmlPath": "/gbdb/ce11/html/description.html",
        "hgNearOk": 0,
        "hgPbOk": 0,
        "sourceName": "C. elegans Sequencing Consortium WBcel235 (GCA_000002985.3)",
        "taxId": 6239,
        "evaSpecies": "caenorhabditis_elegans",
        "trackHubId": "GCA_000002985.3"
    },
    {
        "id": "dm6",
        "name": "D. melanogaster (dm6)",
        "fastaURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/dm6/dm6.fa",
        "indexURL": "https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/dm6/dm6.fa.fai",
        "cytobandURL": "https://s3.amazonaws.com/igv.org.genomes/dm6/cytoBandIdeo.txt.gz",
        "tracks": [
            {
                "name": "Refseq Genes",
                "format": "refgene",
                "url": "https://s3.amazonaws.com/igv.org.genomes/dm6/ncbiRefSeq.txt.gz",
                "indexed": false,
                "order": 1000000,
                "searchable": true
            }
        ],
        "description": "Aug. 2014 (BDGP Release 6 + ISO1 MT/dm6)",
        "nibPath": "/gbdb/dm6",
        "organism": "D. melanogaster",
        "defaultPos": "chr2L:826,001-851,000",
        "active": 1,
        "orderKey": 4067,
        "genome": "D. melanogaster",
        "scientificName": "Drosophila melanogaster",
        "htmlPath": "/gbdb/dm6/html/description.html",
        "hgNearOk": 0,
        "hgPbOk": 0,
        "sourceName": "The FlyBase Consortium/Berkeley Drosophila Genome Project/Celera Genomics (GCA_000001215.4)",
        "taxId": 7227,
        "evaSpecies": "dmelanogaster_6",
        "trackHubId": "GCA_000001215.4"
    },
    {
        "id": "sacCer3",
        "name": "S. cerevisiae (sacCer3)",
        "fastaURL": "https://s3.amazonaws.com/igv.org.genomes/sacCer3/sacCer3.fa",
        "indexURL": "https://s3.amazonaws.com/igv.org.genomes/sacCer3/sacCer3.fa.fai",
        "tracks": [
            {
                "name": "Refseq Genes",
                "type": "annotation",
                "format": "refgene",
                "displayMode": "EXPANDED",
                "url": "https://s3.amazonaws.com/igv.org.genomes/sacCer3/ncbiRefGene.txt.gz",
                "indexed": false,
                "searchable": true
            }
        ],
        "description": "Apr. 2011 (SacCer_Apr2011/sacCer3)",
        "nibPath": "/gbdb/sacCer3",
        "organism": "S. cerevisiae",
        "defaultPos": "chrIV:765966-775965",
        "active": 1,
        "orderKey": 19013,
        "genome": "S. cerevisiae",
        "scientificName": "Saccharomyces cerevisiae",
        "htmlPath": "/gbdb/sacCer3/html/description.html",
        "hgNearOk": 1,
        "hgPbOk": 0,
        "sourceName": "Saccharomyces cerevisiae S288c assembly from Saccharomyces Genome Database (GCA_000146045.2)",
        "taxId": 559292,
        "evaSpecies": "scerevisiae_r64",
        "trackHubId": "GCA_000146045.2"
    }
]